server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/pedidos?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect